src/objects/Array__c.object
<CustomObject>
    <description>An addressable array of sensors, or a single Arduino board.</description>
    <fields>
        <fullName>Array_Address__c</fullName>
        <inlineHelpText>The internet address of this array.</inlineHelpText>
        <label>Array Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Array</label>
    <nameField>
        <displayFormat>Array-{000}</displayFormat>
        <label>Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arrays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Array_Owner__c.object
<CustomObject>
    <description>The owners of this Array</description>
    <fields>
        <fullName>Array__c</fullName>
        <label>Array</label>
        <referenceTo>Array__c</referenceTo>
        <relationshipLabel>Array Owners</relationshipLabel>
        <relationshipName>Array_Owners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User who can control this array</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Array_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Array Owner</label>
    <nameField>
        <displayFormat>Owner {0} from {MM}-{DD}-{YY}</displayFormat>
        <label>Array Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Array Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Command__c.object
<CustomObject>
    <fields>
        <fullName>Action_Confirmation__c</fullName>
        <inlineHelpText>Optional response posted once action confirmation is received from Arduino</inlineHelpText>
        <label>Action Confirmation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Action_Value__c</fullName>
        <inlineHelpText>If setting a non-boolean status, the value for that status</inlineHelpText>
        <label>Action Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actions__c</fullName>
        <inlineHelpText>What action to perform when the Command Text is used. Options are to toggle the object on/off (if applicable), or to set the status of a Thing by providing a value</inlineHelpText>
        <label>Actions</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Command</label>
    <nameField>
        <displayFormat>Command-{00000000}</displayFormat>
        <label>Command</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commands</pluralLabel>
    <recordTypes>
        <fullName>Action</fullName>
        <active>true</active>
        <description>Controls on/off or scaled real world things</description>
        <label>Action</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Chatty2_Callout.cls
global with sharing class Chatty2_Callout {
   
    @future (callout=true)
    global static void doPostCallout(string array_address, string thing_address, id ParentID, id CommandID, string thing_name){
        string response = '';
        Command__c c = [select id, Actions__c, Action_Value__c, Action_Confirmation__c from Command__c where id = :CommandID];
        string commentbody;
        string action;
        
        FeedComment fc = new FeedComment(FeedItemID = ParentId, 
            CreatedByID = Chatty2_Constants.getChattySettings().Chatty2_User__c            
         );
        //change
        if (c.Actions__c == 'On'){
            action = 'HIGH';
        }
        else if (c.Actions__c == 'Off'){
            action = 'LOW';
        }
        else if (c.Actions__c == 'Value'){
            action = c.Action_Value__c;
        }
        else{
        	//throw exceptions
            throw new Chatty2_Constants.ChattyException();
        }

        if (Chatty2_Callout.userOwnsArray(array_address)){        
            try{
                Http h = new http();
                HttpRequest req = new HttpRequest();
                string endpoint = 'http://' + array_address + '/' + thing_address + 
                '/' + action;  
                req.setEndpoint(endpoint);
                system.debug('ENDPOINT: ' + endpoint);        
                req.setMethod('POST');
                req.setHeader('Content-Length', string.valueof(action.length()));
                HTTPResponse res;
                if (!system.Test.isRunningTest()){
                    res = h.send(req); 
                }
                if (res.toString().contains('200') && res.toString().contains('OK')){
                    commentbody = c.Action_Confirmation__c;              
                }
                else{
                    commentbody = 'Uh oh... ' + res.toString();
                }
            }
            catch (Exception e){
                commentbody = e.getMessage();             
            }
            finally{
                fc.CommentBody = commentbody;
                insert fc;
            }
        }
        else{
        	fc.CommentBody = label.ArrayNotOwned;
        	insert fc;
        }    
    }
    
            
    public static string doGetCallout(string thing_name, string array_address){
        string value ='';
        
        if (Chatty2_Callout.userOwnsArray(array_address)){
            try{
                Http h = new http();
                HttpRequest req = new HttpRequest();
                string endpoint = 'http://' + array_address + '/' + thing_name;  
                req.setEndpoint(endpoint);
                system.debug('ENDPOINT: ' + endpoint);        
                req.setMethod('GET');
                req.setHeader('Content-Type', 'application/json');
                HTTPResponse res;
                if (!system.Test.isRunningTest()){
                    res = h.send(req);	
                }
                system.debug('RESPONSE BODY IS: ' + res.getBody());
                JSONParser parser = JSON.createParser(res.getBody());
            
                parser.nextToken();    
                parser.nextValue();
            
                value = parser.getText();
            }
            catch (Exception e){
                value = 'ERROR:  ' + e.getMessage();
            }
            finally{
            	system.debug('VALUE IS===============================' + value);
                return value;   
            }
        }
        else{
        	value = label.ArrayNotOwned;
        }            
                    
        return value;
    }
    
    
    private static boolean userOwnsArray(string array_address){
        set<id> ownerIDs = new set<id>();
        boolean ownsArray = false;
        
    	for (Array_Owner__c a : [select id, User__c from Array_Owner__c where Array__r.Array_Address__c = :array_address]){
            ownerIDs.add(a.User__c);    		
    	}
    	
    	if (ownerIDs.contains(userInfo.getUserId())){
    		ownsArray = true;
    	}
    	
    	return ownsArray;
    }
    
}