src/objects/Array__c.object
<CustomObject>
    <description>An addressable array of sensors, or a single Arduino board.</description>
    <fields>
        <fullName>Array_Address__c</fullName>
        <inlineHelpText>The internet address of this array.</inlineHelpText>
        <label>Array Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Array</label>
    <nameField>
        <displayFormat>Array-{000}</displayFormat>
        <label>Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arrays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Command__c.object
<CustomObject>
    <fields>
        <fullName>Action_Confirmation__c</fullName>
        <inlineHelpText>Optional response posted once action confirmation is received from Arduino</inlineHelpText>
        <label>Action Confirmation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actions__c</fullName>
        <inlineHelpText>What action to perform when the Command Text is used. Options are to toggle the object on/off (if applicable), or to set the status of a Thing by providing a value</inlineHelpText>
        <label>Actions</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Command_Text__c</fullName>
        <inlineHelpText>The text (case insensitive) that triggers this command when used in Chatter</inlineHelpText>
        <label>Command Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Formula_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The command to execute when the status formula is true.</inlineHelpText>
        <label>Formula Response</label>
        <referenceTo>Command__c</referenceTo>
        <relationshipLabel>Commands</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Limit_to_User__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Limit the query results only to those records owned by the calling user.</inlineHelpText>
        <label>Limit to User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <inlineHelpText>Determine how the Chatter message pattern is matched to the available commands. &quot;Starts With&quot; will match only for messages that begin with the command text (excluding any @metions to Chatty).  Contains will match the command text anywhere in a valid post.</inlineHelpText>
        <label>Match Type</label>
        <picklist>
            <picklistValues>
                <fullName>Starts With</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query_Limit__c</fullName>
        <label>Query Limit</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query_Order_By__c</fullName>
        <label>Query Order By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Parameters__c</fullName>
        <inlineHelpText>Query parameters including WHERE, LIMITS and ORDER BY</inlineHelpText>
        <label>Query Parameters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <inlineHelpText>SOQL results to be displayed on request</inlineHelpText>
        <label>Query</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response_Text__c</fullName>
        <inlineHelpText>The optional text Chatty uses to respond when the given command is successfully completed.</inlineHelpText>
        <label>Response Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Formula__c</fullName>
        <inlineHelpText>Optional formula that causes this Command to fire when its Thing&apos;s status meets the formula criteria.</inlineHelpText>
        <label>Status Formula</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Thing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Thing this Command controls (if possible) or provides a reading for (if passive)</inlineHelpText>
        <label>Thing</label>
        <referenceTo>Thing__c</referenceTo>
        <relationshipLabel>Commands</relationshipLabel>
        <relationshipName>Commands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Command</label>
    <nameField>
        <displayFormat>Command-{00000000}</displayFormat>
        <label>Command</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commands</pluralLabel>
    <recordTypes>
        <fullName>Action</fullName>
        <active>true</active>
        <description>Controls on/off or scaled real world things</description>
        <label>Action</label>
    </recordTypes>
    <recordTypes>
        <fullName>Chat</fullName>
        <active>true</active>
        <description>Request and responses from Chatty</description>
        <label>Chat</label>
    </recordTypes>
    <recordTypes>
        <fullName>Query</fullName>
        <active>true</active>
        <description>Performs a dynamic query and returns the results</description>
        <label>Query</label>
    </recordTypes>
    <recordTypes>
        <fullName>Status</fullName>
        <active>true</active>
        <description>Returns the status of a physical Thing. Can also be automatically triggered by reported readings.</description>
        <label>Status</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Thing__c.object
<CustomObject>
    <fields>
        <fullName>Array__c</fullName>
        <label>Array</label>
        <referenceTo>Array__c</referenceTo>
        <relationshipLabel>Things</relationshipLabel>
        <relationshipName>Things</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <inlineHelpText>The manufacturer type for translation purposes</inlineHelpText>
        <label>Component Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thing_Address__c</fullName>
        <inlineHelpText>The name of the Thing. This must be unique and is referenced by the remote Things when calling into Chatty 2.0</inlineHelpText>
        <label>Thing Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thing_Type__c</fullName>
        <inlineHelpText>What type of Thing is this? Digital Things can be on or off. Analog Things provide reading or output based on Chatty commands.</inlineHelpText>
        <label>Thing Type</label>
        <picklist>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analog</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Thing</label>
    <nameField>
        <displayFormat>Thing-{00000000}</displayFormat>
        <label>Thing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Things</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Chatty2_Utilities_TEST.cls
@isTest 
public with sharing class Chatty2_Utilities_TEST {
   
    public static void setupAll(){
        Chatty2_Utilities_TEST.setupTestArrays(1);
    }
    
    public static void setupTestArrays(integer num_of_arrays) {
        
        list<Array__c> arraylist = new list<Array__c>();
        integer i;
        for (i=0; i<=num_of_arrays; i++){
            Array__c a = new Array__c(Array_Address__c = '1.2.3.4.5.6');
            arraylist.add(a);	
        }
        
        insert arraylist; 
        Chatty2_Utilities_TEST.setupTestThings(arraylist, 2);
    }   
     
    public static void setupTestThings(list<Array__c> arraylist, integer things_per_array){
        
        list<Thing__c> thinglist = new list<Thing__c>();
        integer i;
        
        for (Array__c a : arraylist){
            for (i=0; i<= things_per_array; i++){
                Thing__c t = new Thing__c(
                Array__c = a.id,
                Short_Description__c = 'Test Thing ' + i + ' for Array ' + a.Name,
                Thing_Address__c = a.Name + i 
                );	
                
                if (i < 1){
                    t.Thing_Type__c = 'Digital';                	
                }
                else{
                	t.Thing_Type__c = 'Analog';
                }
                
                t.Component_Type__c = 'Boolean';
                
                thinglist.add(t);
            }	
        }
        
        insert thinglist;
        Chatty2_Utilities_TEST.setupTestCommands(thinglist, 4);
    }
   
    public static void setupTestCommands(list<Thing__c> thinglist, integer commands_per_thing){ 
        list<Command__c> commandlist = new list<Command__c>();
        integer i; 
        
        map<id, RecordType> rectypes = Chatty2_Constants.getCommandRecordTypes();
        map<string, id> recmap = new map<string, id>();
        //create a map by string
        for (id rid : rectypes.keyset()){
        	RecordType rt = rectypes.get(rid);
        	recmap.put(rt.Name, rt.id);
        }        
        
        for (Thing__c t : thinglist){
        	for (i=0; i<=commands_per_thing; i++){
        	   
                Command__c c = new Command__c(Thing__c = t.id);
                
                //action
                if (i==0){
                	c.Command_Text__c = 'Test Action Command';
                	c.Match_Type__c = 'Starts With';
                	c.RecordTypeId = recmap.get('Action');
                    c.Response_Text__c = 'Test Response Text';
                    c.Actions__c = 'ON';
                    c.Action_Confirmation__c = 'Test Action Confirmation';	
                }
                //chat
                if (i==1){
                	c.Command_Text__c = 'Test Chat Command';
                	c.Match_Type__c = 'Contains';
                	c.RecordTypeId = recmap.get('Chat');
                	c.Response_Text__c = 'Test Response Text';
                }
                //query
                if (i==2){
                	c.Command_Text__c = 'Test Query Command';
                	c.Match_Type__c = 'Starts With';
                	c.RecordTypeId = recmap.get('Query');
                	c.Query__c = 'select id, Name from Contact';
                	c.Query_Parameters__c = 'LastName != \'TestName\'';
                	c.Query_Order_By__c = 'LastName desc';
                	c.Query_Limit__c = '5';
                	c.Limit_to_User__c = true;                	
                }
                //status
                if (i == 3){
                    c.Command_Text__c = 'Test Status Command';
                    c.Match_Type__c = 'Contains';
                    c.Status_Formula__c = '< 75';
                    c.Formula_Response__c = commandlist[0].id;  
                    c.Response_Text__c = 'Test Response Text';
                    c.RecordTypeId = recmap.get('Status');
                    c.Action_Confirmation__c = 'Test Action Confirmation';
                }
                commandlist.add(c);	
        	}
        } 
        
        insert commandlist;
    }
}