src/objects/Array_Owner__c.object
<CustomObject>
    <description>The owners of this Array</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User who can control this array</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Array_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Array Owner</label>
    <nameField>
        <displayFormat>Owner {0} from {MM}-{DD}-{YY}</displayFormat>
        <label>Array Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Array Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chatty2_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Chatty2_User__c</fullName>
        <inlineHelpText>The user record enabled as Chatty</inlineHelpText>
        <label>Chatty2 User</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Chatty2 Settings</label>
</CustomObject>

src/objects/Thing__c.object
<CustomObject>
    <label>Thing</label>
    <nameField>
        <displayFormat>Thing-{00000000}</displayFormat>
        <label>Thing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Things</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Chatty2_SettingsController.cls
public with sharing class Chatty2_SettingsController {
	
	
	public boolean editUser {get; set;}
	public boolean editLoopback {get; set;}
	
	//borrow this objects user lookup
	public Thing__c thingForUser {get; set;}
	public User ChattyUser {get; set;}
	public Array_Owner__c arrayOwnerForUser {get; set;}
	public Chatty2_Settings__c c2s {get; set;} 
	
	public Chatty2_SettingsController(){
		editUser = false;
		editLoopback = false;		
		
		c2s = Chatty2_Settings__c.getOrgDefaults();
		
		if (c2s.Chatty2_User__c != null){
		  ChattyUser = [select id, Name from User where id = :c2s.Chatty2_User__c];
		  arrayOwnerForUser = new Array_Owner__c(User__c = ChattyUser.id);
		}		      
		else
		  ChattyUser = new User();
	}
	
	
	public pagereference editloopback_config(){
		
		
		return null;
	}
	
	public pagereference edituser_settings(){
		return null;
	}

}