src/objects/Chatty2_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Chatty2_User__c</fullName>
        <inlineHelpText>The user record enabled as Chatty</inlineHelpText>
        <label>Chatty2 User</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Chatty2 Settings</label>
</CustomObject>

src/classes/Chatty2_Contants.cls
public with sharing class Chatty2_Contants {

    public static Chatty2_Settings__c ChattySettings;
    
    public static Chatty2_Settings__c getChattySettings(){
        
        if (ChattySettings == null){
            ChattySettings = Chatty2_Settings__c.getOrgDefaults();        	

            //build default settings
            if (ChattySettings == null){
                id chattyid = [select id from User where LastName = 'Chatter Expert' limit 1].id;            	
            	Chatty2_Settings__c c2s = new Chatty2_Settings__c();
            	c2s.Chatty2_User__c = chattyid;
            	insert c2s;
            }            	
        }
        return ChattySettings;
    }
}