src/objects/Chatty2_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Chatty2_User__c</fullName>
        <inlineHelpText>The user record enabled as Chatty</inlineHelpText>
        <label>Chatty2 User</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Chatty2 Settings</label>
</CustomObject>

src/objects/User_Thing_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>The User ID and associated endpoint for the physical &quot;thing&quot; array for Chatty to communicate with. Different users can have different physical endpoints.</description>
    <label>User Thing URL</label>
</CustomObject>

src/classes/Chatty2_Constants.cls
public with sharing class Chatty2_Constants {
	
    public static Chatty2_Settings__c ChattySettings;
    public static string ChattyName;
    public static list<User_Thing_URL__c> UserURLs;
    
    
    public static Chatty2_Settings__c getChattySettings(){
        
        if (ChattySettings == null){
            ChattySettings = Chatty2_Settings__c.getOrgDefaults();          

            //build default settings
            if (ChattySettings == null){
                id chattyid = [select id from User where LastName = 'Chatter Expert' limit 1].id;               
                Chatty2_Settings__c c2s = new Chatty2_Settings__c();
                c2s.Chatty2_User__c = chattyid;
                insert c2s;
            }               
        }
        return ChattySettings;
    }
    
    public static string getChattyName(){
        
        if (ChattyName == null){
            ChattyName = [select Name from User where id = :ChattySettings.Chatty2_User__c limit 1].Name;
        }
        return ChattyName;
    }
    
    public static list<User_Thing_URL__c> getUserURLs(){
        if (UserURLs == null){
            map<string, User_Thing_URL__c> userURLMap = User_Thing_URL__c.getAll();	
        	for (string s : userURLMap.keySet()){
                UserURLs.add(userURLMap.get(s));        		
        	}
        }    	
    	return UserURLs;
    }
    
    

}